# Файл: .streamlit/secrets.toml
# Помести его в папку .streamlit/ рядом с app.py
# НЕ загружай этот файл на GitHub — добавь в .gitignore

BOT_TOKEN = "8405344522:AAFdt7OVIdVObAvnGwkNOHW28JlR7PTKym4"
ADMIN_ID  = "5980876264"
